# .github/workflows/ci.yml
name: Run JavaScript Tests Unitaires with Karma

on:
  push:
    branches: [main]
    paths-ignore: ['**/*.min.js']
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'  # Ignore les commits de GitHub Actions

    steps:


      - name: Slack Notification
        uses: slackapi/slack-github-action@v1.18.0
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}  # Assurez-vous que ce secret est bien défini
          slack-message: |
            *Workflow Failure Detected*
            *Workflow:* Run JavaScript Tests Unitaires avec Karma
            *Job:* test
            *Commit Message:* Test notification Slack
            *Committer:* Moobotec
            *URL:* https://github.com/moobotec/CodeInputBuilder/actions/runs/11855720353

      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm test

      # Run Minify JavaScript
      - name: Minify JavaScript
        run: npm run minify

      # Upload
      - name: Upload minified file
        uses: actions/upload-artifact@v3
        with:
          name: codeinputbuilder-minified
          path: src/codeinputbuilder.min.js
      
      # Commit
      - name: Commit and Push changes
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/
          git commit -m "Auto-commit: Update minified files" || exit 0  # Exit if nothing to commit
          git push origin HEAD:main

      - name: Slack Notification
        if: failure()
        uses: slackapi/slack-github-action@v1.18.0
        with:
          slack-message: |
            *Workflow Failure Detected*
            *Workflow:* ${{ github.workflow }}
            *Job:* ${{ github.job }}
            *Commit Message:* ${{ github.event.head_commit.message }}
            *Committer:* ${{ github.event.head_commit.committer.name }}
            *URL:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
