# .github/workflows/ci.yml
name: Run JavaScript Tests Unitaires with Karma

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm test

      # Run Minify JavaScript
      - name: Minify JavaScript
        run: npm run minify

      # Upload
      - name: Upload minified file
        uses: actions/upload-artifact@v2
        with:
          name: codeinputbuilder-minified
          path: src/codeinputbuilder.min.js
