# .github/workflows/ci.yml
name: Run JavaScript Tests Unitaires with Karma

on:
  push:
    branches: [main]
    paths-ignore: ['**/*.min.js']
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'  # Ignore les commits de GitHub Actions

    steps:

      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm test

      # Run Minify JavaScript
      - name: Minify JavaScript
        run: npm run minify

      # Upload
      - name: Upload minified file
        uses: actions/upload-artifact@v3
        with:
          name: codeinputbuilder-minified
          path: src/codeinputbuilder.min.js
      
      # Commit
      - name: Commit and Push changes
        if: success()  # Exécuter seulement en cas de succès
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main  # Synchroniser avec les changements distants
          git rebase origin/main # Rebase les changements locaux sur les changements distants
          git add src/
          git commit -m "Auto-commit: Update minified files" || exit 0  # Exit si rien à commit
          git push origin HEAD:main

      - name: Slack Notification
        if: failure() 
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "text": "*Workflow Failure Detected*\n*Workflow:* ${{ github.workflow }}\n*Job:* ${{ github.job }}\n*Commit Message:* ${{ github.event.head_commit.message }}\n*Committer:* ${{ github.event.head_commit.committer.name }}\n*URL:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
