name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier
        run: npm run format -- --check

      - name: Check dependencies licenses
        run: npm run check-licenses

      - name: Slack Notification
        if: failure()
        uses: slackapi/slack-github-action@v1.18.0
        with:
          slack-message: |
            *Workflow Failure Detected*
            *Workflow:* ${{ github.workflow }}
            *Job:* ${{ github.job }}
            *Commit Message:* ${{ github.event.head_commit.message }}
            *Committer:* ${{ github.event.head_commit.committer.name }}
            *URL:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}