name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarQube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Run SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Assurez-vous que SONAR_TOKEN est défini dans vos secrets GitHub
        run: |
          sonar-scanner \
            -Dsonar.projectKey=code-input-builder \
            -Dsonar.sources=src \
            -Dsonar.host.url=http://www.timecaps.io:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
